### ISSUE TITLE
Error 5004, 5002

### ISSUE THREAD

**Issue by theallegrarr** [vobornik/mt4-trade-copy#1]
In the filename parameter, i entered D:\Users\Forbes\AppData\Roaming\MetaQuotes\Terminal\B86ACF179AE0C55FA87E9532FBCA2802\MQL4\Files\TradeCopy

the name of the file is TradeCopy.csv but i either get Error 5004 or Error 5002 

but when i manually copy the file from the master platform to the slave platform files directory, trades are copied

**Comment by HusseinTaha** [comment]
this error is fixed in this patch : https://github.com/HusseinTaha/mt4-trade-copy/tree/patch-2

**Comment by vobornik** [comment]
patch merged, thanks
